[package]
name = "smol-examples"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
smoltcp = {version = "0.12.0", features = ["phy-tuntap_interface", "ethernet"]}
getopts = "0.2"
log = "0.4.4"
url = "2.0"
rand = "0.8"
env_logger = "0.10"
